# ROCm Enabled TensorFlow
- name: Install ROCm packages
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
  - rocm-libs
  - miopen-hip
  - cxlactivitylogger

- name: Install python3-pip
  apt: name={{ item }} state=latest
  with_items:
  - python3-pip

- pip:
    name: virtualenv
    executable: pip3

- pip:
    virtualenv: "/usr/local/tensorflow-rocm"
    name: tensorflow-rocm
